wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1687481312.320493
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.3
      8:
      - 2
      - 4
      - 5
